Repository Fedkasin/lot-management-client, pull requests merged in 2019-04, with the labels that each got.

#37 NO-TICKET - Deploy fixes
  .dockerignore
  bin/start
  docker/bin/clear_containers.sh
  docker/bin/start.sh
  docker/mobilebuilder/Dockerfile
  package.json
Labels: do not merge

#50 [LMC-16] Add filters input check PR #49
  package.json
  src/App.js
  src/components/house/HouseFilter.js
  src/components/house/HouseLotCard.js
  src/components/settings/SettingChildButton.js
  src/components/settings/SettingChildCheckbox.js
  src/components/settings/SettingChildSelect.js
  src/components/settings/SettingChildSlider.js
  src/components/settings/SettingSectionItem.js
  src/constants/Actions.js
  src/constants/Colors.js
  src/containers/HouseFilterContainer.js
  src/containers/HouseWatchFilterContainer.js
  src/containers/HouseWatchLotsContainer.js
  src/helpers/lmapi.js
  src/router/AppTabNavigator.js
  src/store/actions/houseLotsActionCreators.js
  src/store/actions/houseWatchLotsActionCreators.js
  src/store/actions/houseWatchLotsFilterActionCreators.js
  src/store/actions/index.js
  src/store/reducers/houseFilterLiveReducers.js
  src/store/reducers/houseLotsReducers.js
  src/store/reducers/houseWatchLotsReducers.js
  src/store/reducers/index.js
  src/store/sagas/authorizationSaga.js
  src/store/sagas/fetchCarLotsSaga.js
  src/store/sagas/fetchHouseLotsSaga.js
  src/store/sagas/index.js
  src/store/sagas/updateHouseWatchLotsSaga.js
  src/store/sagas/watchHouseLotsSaga.js
  yarn.lock
Labels: enhancement

#52 [LMC-15] - Job operations #40
  assets/images/onlinerby.png
  src/App.js
  src/components/core/IcoButton.js
  src/components/house/HouseFilter.js
  src/components/house/HouseJob.js
  src/constants/Actions.js
  src/constants/Colors.js
  src/constants/Filters.js
  src/constants/Routes.js
  src/containers/HouseWatchFilterContainer.js
  src/containers/HouseWatchLotsContainer.js
  src/containers/JobWatchLotsContainer.js
  src/helpers/lmapi.js
  src/router/AppTabNavigator.js
  src/screens/AuthSignOrRegisterScreen.js
  src/screens/CarLotsScreen.js
  src/screens/HouseFilterScreen.js
  src/screens/HouseLotsScreen.js
  src/screens/HouseWatchFilterScreen.js
  src/screens/HouseWatchLotsScreen.js
  src/screens/JobWatchLotsScreen.js
  src/store/actions/houseWatchLotsActionCreators.js
  src/store/actions/index.js
  src/store/reducers/houseWatchLotsReducers.js
  src/store/sagas/index.js
  src/store/sagas/watchHouseLotsSaga.js
Labels: bug, enhancement

#53 [LMC-13] PR #32 Authentication flow
  assets/images/onlinerby.png
  src/components/core/IonIcon.js
  src/components/house/HouseJob.js
  src/components/house/HouseLotCard.js
  src/containers/HouseWatchLotsContainer.js
  src/containers/SettingsContainer.js
  src/helpers/lmapi.js
  src/screens/HouseWatchFilterScreen.js
  src/screens/HouseWatchLotsScreen.js
  src/store/reducers/houseWatchLotsReducers.js
  src/store/sagas/authorizationSaga.js
Labels: bug
